/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "service": string
      "type": "sst.aws.Service"
    }
    "Gateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "HashidsSalt": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MongoUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}